name: recsys
channels:
  - conda-forge
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates
  - expat=2.7.1
  - libcxx=14.0.6
  - libffi=3.4.4
  - ncurses=6.4
  - openssl=3.0.16
  - pip=25.1
  - python=3.12.0
  - readline=8.2
  - setuptools=78.1.1
  - sqlite=3.45.3
  - tk=8.6.14
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.2.13
  - pip:
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - cramjam==2.10.0
      - fastparquet==2024.11.0
      - filelock==3.18.0
      - fsspec==2025.5.0
      - hydra-core==1.3.2
      - jinja2==3.1.6
      - joblib==1.5.0
      - markupsafe==3.0.2
      - mpmath==1.3.0
      - networkx==3.4.2
      - numpy==1.26.4
      - omegaconf==2.3.0
      - packaging==25.0
      - pandas==2.2.3
      - pillow==11.2.1
      - pydantic==2.11.4
      - pydantic-core==2.33.2
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.2
      - scikit-learn==1.6.1
      - scipy==1.15.3
      - six==1.17.0
      - sympy==1.14.0
      - threadpoolctl==3.6.0
      - torch==2.2.2
      - torchaudio==2.2.2
      - torchvision==0.17.2
      - tqdm==4.67.1
      - typing-extensions==4.13.2
      - typing-inspection==0.4.1
      - tzdata==2025.2
