name: recsys
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.11  # Latest stable Python version
  - numpy
  - pandas
  - pytorch=2.0  # Ensure compatibility with MPS and CUDA
  - torchvision
  - torchaudio
  - tqdm
  - scikit-learn
  - pyyaml
  - matplotlib
  - hydra-core
  - omegaconf
  - pip
  - pip:
      - transformers
      - datasets
      - wandb