defaults:
  - dataloader: distributed
  - model: bert4rec
  - data: movielens
  - trainer: default

dataloader:
  mini_batch_size: ${eval:2**10}
  batch_size: ${eval:2**10}
  num_workers: 4

trainer:
  epochs: 100

pipeline_name: simple
env: pytorch
device: cuda
distributed: true
backend: nccl
