defaults:
  - dataloader: simple
  - model: bert4rec
  - data: movielens
  - trainer: default

dataloader:
  mini_batch_size: 256
  batch_size: 256

trainer:
  epochs: 100

pipeline_name: simple
env: pytorch
device: mps
