defaults:
  - dataloader: distributed
  - model: bert4rec
  - data: movielens
  - trainer: default

dataloader:
  mini_batch_size: ${eval:2**8}
  batch_size: ${eval:2**8}
  num_workers: 0  # MPS often has issues with multiprocessing dataloaders, safer to start with 0

trainer:
  epochs: 200  # Reduced for testing

pipeline_name: simple
env: pytorch
device: cpu
distributed: true
backend: gloo  # MPS/CPU requires gloo

